-- Run this in your Supabase SQL Editor
-- supabase.com → your project → SQL Editor → New Query → paste → Run

-- Inbox table
create table inbox (
  id bigint generated by default as identity primary key,
  text text not null,
  created_at timestamptz default now()
);

-- Projects table
create table projects (
  id bigint generated by default as identity primary key,
  name text not null,
  outcome text default '',
  next_action text default '',
  status text default '🟢 Active',
  area text default 'Work',
  created_at timestamptz default now()
);

-- Someday table
create table someday (
  id bigint generated by default as identity primary key,
  text text not null,
  created_at timestamptz default now()
);

-- Enable public access (since this is a personal app)
alter table inbox enable row level security;
alter table projects enable row level security;
alter table someday enable row level security;

create policy "Allow all" on inbox for all using (true) with check (true);
create policy "Allow all" on projects for all using (true) with check (true);
create policy "Allow all" on someday for all using (true) with check (true);
